version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker images for microservices
          command: |
            curl -fsSl https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed $USERNAME/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user $USERNAME/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend $USERNAME/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy $USERNAME/udagram-reverseproxy:v1

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            docker push $USERNAME/udagram-api-feed:v1
            docker push $USERNAME/udagram-api-user:v1
            docker push $USERNAME/udagram-frontend:v1
            docker push $USERNAME/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
